// RULES IN Patterns

/*
 * .1. IF VALUE IS NOT CHANGING IN SAME ROW THEN THINK OF 'I'TO PRINT IT.
 * 
 * .2.IF VALUE IS NOT CHANGING IN COLOUMN THEN THINK OF 'J' TO PRINT IT.
 * 
 * .3. MID FORMULAE MID =(N/2) +1.
 * 
 */